# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx690tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.cache/wt [current_project]
set_property parent.project_path /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc709:part0:1.8 [current_project]
set_property ip_output_repo /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/sources/fixed_2_float.v
  /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/sources/lzc.v
  /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/sources/pe_array1x3_lower.v
  /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/sources/pe_array1x3_middle.v
  /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/sources/pe_array1x3_upper.v
  /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/sources/pe_array3x3.v
}
read_ip -quiet /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/mult8_8/mult8_8.xci
set_property used_in_implementation false [get_files -all /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/mult8_8/mult8_8_ooc.xdc]

read_ip -quiet /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder_hfp/adder_hfp.xci
set_property used_in_implementation false [get_files -all /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder_hfp/adder_hfp_ooc.xdc]

read_ip -quiet /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder16_16/adder16_16.xci
set_property used_in_implementation false [get_files -all /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder16_16/adder16_16_ooc.xdc]

read_ip -quiet /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder17_16/adder17_16.xci
set_property used_in_implementation false [get_files -all /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder17_16/adder17_16_ooc.xdc]

read_ip -quiet /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder18_18/adder18_18.xci
set_property used_in_implementation false [get_files -all /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder18_18/adder18_18_ooc.xdc]

read_ip -quiet /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder18_19/adder18_19.xci
set_property used_in_implementation false [get_files -all /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder18_19/adder18_19_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top pe_array3x3 -part xc7vx690tffg1761-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pe_array3x3.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file pe_array3x3_utilization_synth.rpt -pb pe_array3x3_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
