# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder_hfp/adder_hfp.xci
# IP: The module: 'adder_hfp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder_hfp/adder_hfp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_hfp'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder_hfp/adder_hfp.xci
# IP: The module: 'adder_hfp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder_hfp/adder_hfp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_hfp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
