webtalk_init -webtalk_dir /home/dai/vgg16.sparse.5x/vgg16.sparse.5x.sim/sim_1/behav/xsim/xsim.dir/pe_array1x3_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 22 19:43:14 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c782e5fc-ffac-4071-b9b3-a276c858c3df" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a9ee8fa84b2045a88c942534907ab979" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3591.705 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "328550 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.59_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125760_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1807788934 -regid "" -xml /home/dai/vgg16.sparse.5x/vgg16.sparse.5x.sim/sim_1/behav/xsim/xsim.dir/pe_array1x3_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/dai/vgg16.sparse.5x/vgg16.sparse.5x.sim/sim_1/behav/xsim/xsim.dir/pe_array1x3_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/dai/vgg16.sparse.5x/vgg16.sparse.5x.sim/sim_1/behav/xsim/xsim.dir/pe_array1x3_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
