# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dai/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder16_16/adder16_16.xci
# IP: The module: 'adder16_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dai/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder16_16/adder16_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder16_16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/dai/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder16_16/adder16_16.xci
# IP: The module: 'adder16_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dai/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/adder16_16/adder16_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder16_16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
