# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/mult8_8/mult8_8.xci
# IP: The module: 'mult8_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/mult8_8/mult8_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult8_8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/mult8_8/mult8_8.xci
# IP: The module: 'mult8_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daijw/vgg16.sparse.5x/vgg16.sparse.5x.srcs/sources_1/ip/mult8_8/mult8_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult8_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
